FROM python:latest


WORKDIR ./
#to COPY the remote file at working directory in container
COPY demo.py requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt 

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./demo.py"]